---
id: fbf37f0d-f8ce-4cb8-80fc-edb8299c2be2
registrations:
  - validity:
      - input:
          model: { id: 92090f32-4539-47a7-a93e-ed185251802f, name: UI Model }
          class: { id: 12b4049a-fb65-4429-a9d7-c91d88a58ac9, name: Class }
          name: Orgviewer Configuration
          description: >-
            A configuration of the orgviewer application which determines a
            specific set of property sheets
          attributes:
            treeNodeTemplate:
              description: >-
                Optional template string used for customizing the tree nodes in
                the orgviewer hierarchy table
              dataType: string
          singleRelations:
            tenant:
              description: For use if this is a tenant-specific configuration
              id: 41e0ef9b-01f3-41fd-aa39-6bcb40374704
              name: Tenant
          manyRelations:
            propertySheets:
              description: Property Sheets to use for the Orgviewer
              id: e81c542d-76c9-4396-af3a-39c223c1a5a4
              name: Property Sheet
        from: 1900-01-01T00:00:00.000Z
...
