# Rule Application Class
---
id: cb70fe97-13bd-4471-8f5f-a050c7f463bb
mimeType: application/vnd.reflective-dk.object+json
registrations:
  - validity:
      - input:
          model: { id: 'd341451b-d971-4656-bac2-1783776f8efe' }
          # Responsible actor - actor: { id: actor.id }
          class: class:core:class
          classId: class:core:rule-application
          extends: class:core:object
          name: RuleApplication
          description: >-
            This class activates a specific set of rules by assigning them to a
            set of object types
          properties:
            model:
              description: Relation to the model that owns this rule application
              type: simple
              dataType:
                type: relation
                target: class:core:model
            rules:
              description: The rules to apply
              type: map
              dataType:
                type: relation
                target: class:core:rule
            types:
              description: The types for which to apply the rules
              type: map
              dataType:
                type: relation
                target: class:core:class
...
